runtime: python37

automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: static
  expiration: "31557600s"
- url: /dist
  static_dir: dist 
- url: /.*
  secure: always
  script: auto